#Configuration
#Thu Feb 26 12:46:23 MST 2026
ADD_FILE_DIRECTORY=/Users/hyrumreynolds/Downloads/Chunker Testing
FUNCTION_PHRASE_FILE=/Users/hyrumreynolds/Downloads/Chunker Testing/Fake.xlsx
SAVE_CHUNKS_DIRECTORY=/Users/hyrumreynolds/Downloads/Chunker Testing
SAVE_EVALUATION_DIRECTORY=/Users/hyrumreynolds/Downloads/Chunker Testing
