#Configuration
#Tue Feb 24 10:18:58 MST 2026
ADD_FILE_DIRECTORY=/Users/hyrumreynolds/Downloads/Chunker Testing
FUNCTION_PHRASE_FILE=/Users/hyrumreynolds/Downloads/Chunker Testing/Fake.xlsx
SAVE_CHUNKS_DIRECTORY=/Users/hyrumreynolds/Downloads/Chunker Testing
SAVE_EVALUATION_DIRECTORY=/Users/hyrumreynolds/Downloads/Chunker Testing
